### ISSUE TITLE
Unpredicable hangs

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/dmsg#1]
@evanlinjin commented 28 days ago

Describe the bug

As we are now using dmsg as the means of communication between Visor and Setup Nodes in skywire, we realized during writing tests for the setup module, that the tests are unpredictable.

Sometimes they pass, sometimes they fail, and sometimes they hang.

The current assumption is that, in the low-latency, high-throughput environment of local testing, dmsg may hang when communication begins too early after Dail/Accept.

After adding a sleep before each write, the tests ended up being predictable.

**Comment by vidya88** [comment]
@Darkren commented 22 days ago

@evanlinjin from my observation I'd say that with a sleep tests become more predictable but with different sleep durations I still experience hanging. Also there are some strange issues - I get context deadline exceeded while using context.TODO(). Probably we're dealing with a mix of problems here. I'm working on it

**Comment by vidya88** [comment]
@Darkren commented 22 days ago

@evanlinjin I see, we enforce timeout on read/write operations in the setup protocol. That's where context deadline exceeded comes from. If I put sleep as stated above and increase setup proto read timeout to, say, 100 seconds, test passes. But if we do that on each request, how is this possible that the test hangs? Shouldn't each request be interrupted at least when we exceed this timeout? Probably context is being misused somewhere. The whole rule setup should get interrupted on receiving this error, but it doesn't. I guess the 2 major problems here are:

1. Assumed misuse of context
2. Hanging bug in the DMSG which doesn't allow to deliver messages on time for a timeout not to be exceeded
I'll start with the 1st. As soon as it gets sorted, test should be failing or passing each time without hanging. Pass means everything is ok, failure in this case will happen only when DMSG hangs and read timeout gets exceeded. Then when I deal with the 2nd, test should always pass

**Comment by vidya88** [comment]
@evanlinjin commented 22 days ago

@evanlinjin I see, we enforce timeout on read/write operations in the setup protocol. That's where context deadline exceeded comes from. If I put sleep as stated above and increase setup proto read timeout to, say, 100 seconds, test passes. But if we do that on each request, how is this possible that the test hangs? Shouldn't each request be interrupted at least when we exceed this timeout? Probably context is being misused somewhere. The whole rule setup should get interrupted on receiving this error, but it doesn't. I guess the 2 major problems here are:

1. Assumed misuse of context

2. Hanging bug in the DMSG which doesn't allow to deliver messages on time for a timeout not to be exceeded

I'll start with the 1st. As soon as it gets sorted, test should be failing or passing each time without hanging. Pass means everything is ok, failure in this case will happen only when DMSG hangs and read timeout gets exceeded. Then when I deal with the 2nd, test should always pass

Personally I haven't encountered a situation where context.Context is misused... I may be wrong, but it seems that context.Context is hard to misuse. Anyway, keep me updated.

**Comment by vidya88** [comment]
@Darkren commented 22 days ago

@evanlinjin It doesn't mean that I haven't messed up with the context in the rule setup :) it could all be my mistake somewhere. I'll check everything

**Comment by evanlinjin** [comment]
This is inappropriate and the issue has been resolved.
