### ISSUE TITLE
Add Ping method to dmsg.Client

### ISSUE THREAD

**Issue by jdknives** [SkycoinProject/dmsg#110]
**Feature description**

The dmsg.Client should be able to:

- [x] list the remote clients it is connected to
- [x] list the servers used for each remote client
- [x] send a Ping to the remote and receive a pong to calculate roundtrip time

**Is your feature request related to a problem? Please describe.**
Related to feature for hypervisor requested by Synth here: https://github.com/SkycoinProject/skywire-mainnet/issues/407

**Comment by evanlinjin** [comment]
@jdknives For point `send a Ping to the remote and receive a pong to calculate roundtrip time`, are we wanting to calculate roundtrip time between client/server or between client/client?
