### ISSUE TITLE
Improve logging of entry loop

### ISSUE THREAD

**Issue by jdknives** [SkycoinProject/dmsg#111]
**Describe the bug**
Maybe this is not technically a bug, but the dmsgpty host logs every update of the entry currently. Since we added a loop to validate entries of clients, that means it logs the full entry to stdout, which makes it harder to get the relevant logs. 
<img width="636" alt="Bildschirmfoto 2020-06-18 um 16 37 16" src="https://user-images.githubusercontent.com/36450093/85034071-fa82e000-b181-11ea-9a88-18ce576ac942.png">

**Comment by evanlinjin** [comment]
@jdknives Would just making it use log level `DEBUG` work?

**Comment by jdknives** [comment]
> @jdknives Would just making it use log level `DEBUG` work?

Yes.
