### ISSUE TITLE
Define `SetDeadline()`, `SetReadDeadline()` and `SetWriteDeadline()` for `Transport` properly

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/dmsg#16]
@nkryuchkov commented on Aug 14

`SetDeadline()`, `SetReadDeadline()` and `SetWriteDeadline()` are not implemented for `Transport`, therefore ones implemented for `net.Conn` are used.

**Comment by evanlinjin** [comment]
Implemented in #37
