### ISSUE TITLE
EOF error in `TestNewClient`

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/dmsg#19]
@nkryuchkov commented on Jul 2

**Describe the bug**
During the implementation of [#2](https://github.com/skycoin/dmsg/pull/2) `TravisCI` failed with `EOF` error in `TestNewClient` in `a21feaa `commit.

This is a floating bug. After failed `TravisCI` build, I was unable to reproduce the bug.

**Environment information:**

- TravisCI

**Steps to Reproduce**

1. Run `TravisCI` build

**Actual behavior**
`TestNewClient` fails with `EOF` error (panic is raised by test itself).

**Expected behavior**
`TestNewClient` passes.

**Additional context**
Failed `TravisCI` build link:
https://travis-ci.com/skycoin/dmsg/builds/117521843

**Possible implementation**
For the commit [`a21feaa`](https://github.com/skycoin/dmsg/commit/a21feaabd2a07db38ab8d426095149d67ffb8e1c) the lines where the error may occur are between `811` and `817`.

**Comment by evanlinjin** [comment]
Invalidated by #37
