### ISSUE TITLE
Not able to send payload between two nodes after Transport is successfully established

### ISSUE THREAD

**Issue by sn-srdjan** [SkycoinProject/dmsg#2]
**Describe the bug**
After handshake is established between requestor and responder it's not clear on how to exchange messages between those two.
From example code found here it's clear that bytes can be sent around, but it's unclear on how to achieve the same thing by reacting on events instead of sequentially sending Writes and performing Reads.
Main part of the issue is located on requestor's side at [this line](https://github.com/sn-srdjan/dmsg-http/blob/f51504980a8277c2bc4ab99a56c076b20b1f6652/transport.go#L53). When message is written using obtained Transport instance nothing is read on the responder's side. Responder's connection to DMSG Server is obtained [here](https://github.com/sn-srdjan/dmsg-http/blob/f51504980a8277c2bc4ab99a56c076b20b1f6652/server.go#L29).

**Environment information:**

- OS: Mac OS X
- Platform: Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Steps to Reproduce**

1. Run local discovery on localhost:9090 using skycoin repo on branch mainnet-milestone1 (./bin/messaging-discovery --redis redis://localhost:32768) - redis instance is needed on 32678 or any port. Alternatively use mock or global discovery, with modification in the test
2. Run local dmsg server from skycoin repo on branch mainnet-milestone1 (./bin/messaging-server cmd/messaging-server/config.json -m :2122) config.json is added in Additional context section
3. Clone repo from https://github.com/sn-srdjan/dmsg-http and checkout branch use-transport-for-making-request
4. Run test TestDMSGClient found in dmsg-http_test.go
5. Observe in the server and console logs that no communication is happening after message is written from requestor towards responder via successfully opened Transport

**Actual behavior**
Nothing happens. Test is successful because it doesn't assert response, but there's no point in asserting right now because mechanism for listening on responder's response is not setup yet.
I'm maybe missing code needed to run after handshake is completed, if that's the case please point me in the right direction.

**Expected behavior**
Message is read by requester properly so it can handle it and respond to it.

**Additional context**
cmd/messaging-server/config.json content is:
{
  "public_key": "035915c609f71d0c7df27df85ec698ceca0cb262590a54f732e3bbd0cc68d89282",
  "secret_key": "6eddf9399b14f29a60e6a652b321d082f9ed2f0172e02c9d9c1a2a22acf4bee3",
  "discovery": "http://localhost:9090",
  "public_address": "localhost:8080",
  "local_address": ":8080",
  "log_level": "info"
}

**Comment by evanlinjin** [comment]
> When message is written using obtained Transport instance nothing is read on the responder's side.
Where is your call to `(*dmsg.Transport).Read()`?

**Comment by evanlinjin** [comment]
There is no bug, the example given displays bad use of the library. The PR: https://github.com/sn-srdjan/dmsg-http/pull/3 fixes the example code.

**Comment by SNChris** [comment]
Thanks for the clarification!
