### ISSUE TITLE
Implement exponential backoff.

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/dmsg#20]
@evanlinjin commented on Jul 1

**Feature description**

Here:

> dmsg/client.go
> 
> Line 483 in 6bd3123
> 
>  case <-time.After(clientReconnectInterval): 

**Additional context**

[skycoin/skywire#459 (comment)](https://github.com/skycoin/skywire/issues/459#issuecomment-507216449)

**Comment by jdknives** [comment]
Based on testing, this has been partially implemented in #55 . The client uses exponential backoff for calls to discovery but not to server.
