### ISSUE TITLE
nettest.TestConn fails with noise.Conn and dmsg.Transport

### ISSUE THREAD

**Issue by nkryuchkov** [SkycoinProject/dmsg#21]
The tests implemented in #9 for `noise.Conn` (`RacyRead` and `ConcurrentMethods`) and `dmsg.Transport` fail . It looks like the `noise.Conn` implementation has concurrency issues. The race detector also finds a data race.

The `dmsg.Transport` test failure might be related to #27.

**Comment by nkryuchkov** [comment]
Most of the issues are fixed in #9 and #29. There's one issue left that happens under very rare conditions. When calling a lot of concurrent `net.Conn` methods, `noise.Conn` hangs sometimes.

**Comment by nkryuchkov** [comment]
We need to put it on hold until https://github.com/SkycoinProject/dmsg/pull/37 is implemented and check if the issue still exists then.

**Comment by evanlinjin** [comment]
Fixed in #37
