### ISSUE TITLE
EOF when returning http response using buffered writer (bufio) in golang

### ISSUE THREAD

**Issue by sn-srdjan** [SkycoinProject/dmsg#38]
**Describe the bug**
When [http-dmsg](https://github.com/SkycoinProject/dmsg-http) is used to serve and consume content over dmsg protocol different behaviour is seen when file is returned without the use of the buffer and with it.
For smaller content response is returned correctly but when larger content is sent over dmsg EOF error is caught when reading the response is taking place.

Example [commit](https://github.com/SkycoinPro/cxo-2-node/pull/32/commits/c88f9cc7a489a8cc826ca8b5c84d6946e4bb2370) is created adding one dummy http server that provides data via dmsg protocol. It has two handlers - /small and /large that return different sizes of strings.
There is also example of the client that consumes this server. Once response of /small handler is checked everything is ok and in that case content is too small for buffered response writer to be used. However, when we invoke /large path buffered writer is used and on first b.Flush() invoked within [bufio.go](https://golang.org/src/bufio/bufio.go):629 as part of buffered response - communication is broken, read bytes stops on the client side and unexpected EOF is thrown as error.

**Environment information:**

- OS: Mac OS X
- Platform: Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Steps to Reproduce**

1. Checkout provided [branch](https://github.com/SkycoinPro/cxo-2-node/pull/32) from cxo-2-node project
2. Run '/cmd/server/http-server.go' from that project
3. Make a note of server's public key address printed out in first few lines during startup (for example "Starting http server on public key: 029ef186ed87484fe358ee2454c6140286c0f667fc59bce8351755b642e33def9b and port: 9090"
4. Copy pub key value into serverPubKey variable placed under /cmd/client/http-client.go:18
5. Run /cmd/client/http-client.go

**Actual behavior**
Invocation of /small handler on the provided dummy server is successful but /large handler fails when read from the client side - "http: unexpected EOF reading trailer" is returned 

**Expected behavior**
Both /small and /large handlers should be read correctly from the client when they are invoked.

**Additional context**
What might be the case is for RoundTrippier implementation within dmsg-http project to be incorrect, and that it should handle these buffered responses, but since both writing using buffer and reading from it are part of the bufio library, that doesn't make too much sense.

**Comment by evanlinjin** [comment]
@sn-srdjan what happened to isolating code to pin down the problem? And instead of providing a link to the branch, it will be easier to just give me the name of the branch in the future. Saves time for me not having to search around.

**Comment by jdknives** [comment]
According to @sn-srdjan this isssue is still present in `dmsg@mainnet-milestone2` @evanlinjin

**Comment by sn-srdjan** [comment]
I can confirm that the PR https://github.com/SkycoinProject/dmsg/pull/42/files created by @evanlinjin is fixing this issue.

**Comment by jdknives** [comment]
Fixed by #42
