### ISSUE TITLE
Investigate dmsg.Discovery crash

### ISSUE THREAD

**Issue by jdknives** [SkycoinProject/dmsg#39]
**Describe the bug**
Every other week, the dmsg.Discovery seems to crash for yet unknown reasons. This should be fixed before mainnet migration.

**Comment by evanlinjin** [comment]
@jdknives It will be good if someones goes and retrieves the discovery logs before crash.

**Comment by jdknives** [comment]
@evanlinjin I cannot retrieve the logs this time. Next time it happens, I will get them before I restart.

**Comment by evanlinjin** [comment]
@jdknives Is this still happening?

**Comment by jdknives** [comment]
@evanlinjin has not happened for a while. I will close this. In case, this happens again, we have improved the logging so next time we can investigate.
