### ISSUE TITLE
Dmsg server stops stream with error 307

### ISSUE THREAD

**Issue by jdknives** [SkycoinProject/dmsg#50]
**Describe the bug**
The `dmsg.Server` logs the following errors on the skywire.cc deployment right now. 

![unknown](https://user-images.githubusercontent.com/36450093/73352093-a9d12000-4290-11ea-9c0c-27e2c1c3b056.png)

This leads to `visors` not being able to establish a connection with a `dsmg.Server`.

**Comment by evanlinjin** [comment]
I don't think there is enough proof here to say that this is a bug. The error means that the next session does not exist and the request cannot be forwarded.

This happens when client `A` wants to create a stream to `B` via server `C` like so: `A -> B -> C` but `B -> C` does not exist.
